eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9003
spring:
  application:
    name: service-gateway
zuul:
  routes:
    security:
      path: /security/**
      serviceId: service-security
    sdk-service:
      path: /v*/**
      serviceId: service-security
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign